Redirect to URL if Request is not AJAX
CottaCush/yii2-utils pull request #25
Opened 2017-06-30 14:15 UTC by yemexx1

2017-07-01 01:04 UTC, goke-epapa commented on src/Controller/BaseController.php
> +                return $this->redirect($this->getRequest()->getReferrer());
You need to handle cases where `getReferrer()` returns `null`.

2017-07-01 01:04 UTC, goke-epapa requested changes
Good work, requested a change.

2017-07-03 09:16 UTC, netwox approved these changes

2017-07-03 14:23 UTC, goke-epapa approved these changes

2017-07-03 14:24 UTC, merged